# Generated by Django 5.2.4 on 2025-07-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
