# Generated by Django 5.2.4 on 2025-07-31 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role__in': ['owner', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='turf', to=settings.AUTH_USER_MODEL),
        ),
    ]
