# Generated by Django 5.2.4 on 2025-07-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0002_turf_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='turf',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='turf.amenity'),
        ),
    ]
