# Generated by Django 5.2.4 on 2025-07-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0002_alter_turf_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
