# Generated by Django 5.2.4 on 2025-08-02 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0004_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
