# Generated by Django 5.2.4 on 2025-07-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0004_alter_turf_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='minimum_booking_duration',
            field=models.IntegerField(default=1),
        ),
    ]
