# Generated by Django 5.2.4 on 2025-08-03 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0005_alter_turf_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfbooking',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bokkings', to='turf.turf'),
        ),
    ]
