# Generated by Django 5.2.4 on 2025-08-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0007_alter_turfbooking_turf'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfbooking',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
